### ISSUE TITLE
Issue with some first year courses

### ISSUE THREAD

**Issue by shikharsoni07** [metakgp/gyft#100]
When logging in with a first year roll number, the following error occurred:

ss:
![image](https://github.com/metakgp/gyft/assets/139053348/9c6c761c-6550-4580-8c51-4aafabdbfa25)

P.S.: only checked with one first year roll number (mine).

**Comment by ashwinpra** [comment]
Seems to be working when I hardcode the semester value and try to fetch, so I feel like it might be some problem with first years' ERP interface.
@shikharsoni07 could you please show what comes up when you navigate to this page? `Academic -> Students -> Your Academic Information -> Performance New -> Curr. and Perf. Semno 1`

**Comment by shikharsoni07** [comment]
@ashwinpra 

![Screenshot_20230813-210445.png](https://github.com/metakgp/gyft/assets/139053348/b308c694-3e8c-42ce-b677-a480b23873e5)

I think the problem is only for the CS course. Maybe try changing it to "CS10003"
