### ISSUE TITLE
POA: WebApp and beyond

### ISSUE THREAD

**Issue by proffapt** [metakgp/gyft#105]
- [x] Modularisation of `gyft.py` into
   > **Note** Time table extractor will be imported in both - obviously.
   - [x] Timetable extractor  - @Devansh-bit 
   - [x] CLI workflow(login) - @Devansh-bit 
   - [x] WebApp workflow (login) [<- __This is backend__] - #132 
- [x] https://github.com/metakgp/gyft/issues/128
- [x] Archive [gyft-serve](https://github.com/metakgp/gyft-serve)
- [x] #134
- [x] #133

**Comment by rohan-b-84** [comment]
I'm working on the frontend for gyft using svelte

**Comment by Vector-013** [comment]
Hi could you please explain the expectations in the login workflow?

**Comment by ashwinpra** [comment]
Assigning the workflow part to @Vector-013 after discussion on Slack.

**Comment by tanush-128** [comment]
Is there anyone working on this issue currently? If not can I work on this issue?
I would suggest developing web app using nextjs

**Comment by Ananya-m0140** [comment]
I would also like to work and assist on this issue.

**Comment by ashwinpra** [comment]
@tanush-128 and @Ananya-m0140:  check [this](https://github.com/metakgp/gyft/pull/115) PR by Rohan - some work had already been done but some functionalities are pending. You may discuss this with @rohan-b-84 on MetaKGP Slack and proceed accordingly
