### ISSUE TITLE
no module named bs4

### ISSUE THREAD

**Issue by Annie-1-code** [metakgp/gyft#117]
On typing
 python3 gyft.py
we get
Traceback (most recent call last):
  File "C:\Users\Anindita\OneDrive\Desktop\gyft\gyft.py", line 2, in <module>
    from timetable import delete_calendar, create_calendar, build_courses, generate_ics
  File "C:\Users\Anindita\OneDrive\Desktop\gyft\timetable\__init__.py", line 1, in <module>
    from timetable.extractor import *
  File "C:\Users\Anindita\OneDrive\Desktop\gyft\timetable\extractor.py", line 4, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by rajivharlalka** [comment]
Did you install the packages?

**Comment by Annie-1-code** [comment]
Yes I did

**Comment by chirag-ghosh** [comment]
Please share all the commands you ran and the terminal output for each one of them

**Comment by Annie-1-code** [comment]
Anindita@LAPTOP-2SLSKM5I MINGW64 ~
$ cd gyft
bash: cd: gyft: No such file or directory

<img width="439" alt="Screenshot_13" src="https://github.com/metakgp/gyft/assets/78497125/c08fe0ca-220c-485f-a147-e9b73159ee27">
<img width="440" alt="Screenshot_12" src="https://github.com/metakgp/gyft/assets/78497125/3bb955ee-1798-42d4-b55e-b6d570367d79">
<img width="440" alt="Screenshot_11" src="https://github.com/metakgp/gyft/assets/78497125/ccb0e595-1327-4d73-a7e1-d1e518f1ba42">
<img width="434" alt="Screenshot_10" src="https://github.com/metakgp/gyft/assets/78497125/52315a94-2eb7-4b92-977f-51aa3b2af4a3">
<img width="433" alt="Screenshot_9" src="https://github.com/metakgp/gyft/assets/78497125/11f0c23a-06ec-4cb4-9e18-2c4bd59555e9">
<img width="433" alt="Screenshot 8" src="https://github.com/metakgp/gyft/assets/78497125/75f1d2a3-f071-48da-bc0f-da29a6eaf484">
<img width="430" alt="Screenshot 7" src="https://github.com/metakgp/gyft/assets/78497125/ae98425b-da72-4644-b616-ad6b41dc5791">
<img width="440" alt="Screenshot_6" src="https://github.com/metakgp/gyft/assets/78497125/9e25b879-3c0e-4e1f-8132-9f8163f1d7e2">
