### ISSUE TITLE
Implement a deployment workflow

### ISSUE THREAD

**Issue by proffapt** [metakgp/gyft#133]

**Comment by Bikram-ghuku** [comment]
Can I work on this issue?

**Comment by proffapt** [comment]
Pehle bann toh jane do

**Comment by Bikram-ghuku** [comment]
okay

**Comment by proffapt** [comment]
@Bikram-ghuku read the workflows in gyfe, [here](https://github.com/metakgp/gyfe/tree/main/.github/workflows) and implement similar pipeline for it. Also the code is not ready yet so the PR will be merged after the code is done.

**Comment by proffapt** [comment]
DONE :)
