### ISSUE TITLE
Frontend in `Svelte`

### ISSUE THREAD

**Issue by proffapt** [metakgp/gyft#134]

**Comment by harshkhandeparkar** [comment]
@proffapt Is someone working on this? Why is it "In Progress"?

**Comment by proffapt** [comment]
> @proffapt Is someone working on this? Why is it "In Progress"?

This was implemented in #115. @rohan-b-84 please ask the one currently working on this task to comment here and get this issue assigned to them.

**Comment by proffapt** [comment]
Done

**Comment by proffapt** [comment]
Done in #136
