### ISSUE TITLE
Timetable scraping throws error for misaligned ERP Timetable rows

### ISSUE THREAD

**Issue by athityakumar** [metakgp/gyft#18]
Test case : 

For roll number 14IE10029 , `gyft.py` fails with error `Key error 7` for `timetable_dict[days[i]] = {}`. So, days is initialized from 1 to 6, and yet due to misalignment of rows in ERP timetable, it tries to access `days[7]` which throws an error.

<img src = "https://scontent.fdel1-2.fna.fbcdn.net/v/t35.0-12/14001687_1029835160470459_470665149_o.png?oh=4835f17f89d23f3b3cddcded2608d5cc&oe=57B51204">

**Comment by thealphadollar** [comment]
I'll be working on this; hasn't been fixed yet.
