### ISSUE TITLE
Sync to Google calendar - select dates intelligently

### ISSUE THREAD

**Issue by athityakumar** [metakgp/gyft#23]
Improvisation in selecting date periods : 

(1) The Sync should be made to the Google Calendar, only till beginning of end-semester exams. Currently, the sync is made for all weeks after the current week.
(2) The week of mid-semester / end-semester exams should be left vacant at least, or even better - be filled with the user's mid-semester / end-semester timetable.

**Comment by dultimate** [comment]
What to do with this error upon trying python add_events.py
![screenshot from 2016-12-19 21-14-06](https://cloud.githubusercontent.com/assets/24244580/21318722/6ad3b5dc-c630-11e6-9ff3-6cf552cfdb7a.png)

**Comment by icyflame** [comment]
Closed in favor of #33
