### ISSUE TITLE
Del_events.py won't be able to select only gyft events

### ISSUE THREAD

**Issue by athityakumar** [metakgp/gyft#25]
Previously, we searched for regex `Class of` or `Lab of` in `del_events.py` to choose only events added by `gyft` and then delete them. But after merging of PR #15 , this regex will no longer be valid. We need some other way to delete `gyft` events from Google Calendar.

Ping @icyflame @nishnik @DefCon-007 @kshitij10496

**Comment by icyflame** [comment]
@athityakumar I think events have something called "Notes", you can add some unique text such as 
```
---
DO NOT type or remove below this line.
Added by Gyft (github.com/metakgp/gyft)
```

This will give us exactly the set of all Gyft events.

**Comment by athityakumar** [comment]
@icyflame - Have a look at the fields supported by the API : https://developers.google.com/google-apps/calendar/v3/reference/events#resource
We can probably add 
`event["source"]["url"] = "https://github.com/metakgp/gyft"` and/or `event["source"]["title"] = "GYFT , METAKGP"`.

**Comment by icyflame** [comment]
@athityakumar Is this only for Google Calendar API? You can use it. I was thinking of a way to do it in a generic manner (This would work even for ICS files).
