### ISSUE TITLE
Using insti proxy with httplib2

### ISSUE THREAD

**Issue by athityakumar** [metakgp/gyft#28]
Currently, line 77 of `add_events.py` throws socket error due to insti proxy.

Modification required is : 
`http = credentials.authorize(httplib2.Http(proxy_info = httplib2.ProxyInfo(httplib2.socks.PROXY_TYPE_HTTP_NO_TUNNEL, '10.3.100.207', 8080)))`

**Comment by athityakumar** [comment]
Did anyone else face this problem?
Ping @icyflame @vivekiitkgp @nishnik @DefCon-007 @hargup

**Comment by vivekiitkgp** [comment]
I don't remember ever directly interacting with any httplib library in Python. Never had to face any such issues when using `requests` library.

**Comment by DefCon-007** [comment]
@athityakumar : It also works fine on my system. Check if the proxy is setup on zsh config file

**Comment by athityakumar** [comment]
Proxy config is of course setup at `~/.zshrc` - yet, I still do face this issue. Might this have something to do with `Python 2.x - Python 3.x` (I used `Python 2.x), or just with how my internet connection is setup (Phone connects to KGP Wifi, and and then the Laptop gets internet from the phone with USB Tethering)?

**Comment by vivekiitkgp** [comment]
Probably. Since it's a specific issue, we can close this issue. But of course, feel free to add any solution you find later.

**Comment by athityakumar** [comment]
Sure, the solution is already there in the Issue's first comment - if anyone faces this issue. Closing this issue now. :smile:

**Comment by icyflame** [comment]
@athityakumar This kind of an issue is not helpful when someone is running the script, even less helpful if the issue is closed. Why not put this into the script and get a flag from the user? If they pass the flag, when they run `add_events.py`, then use the proxy otherwise not.

**Comment by icyflame** [comment]
@athityakumar I meant something like this: https://github.com/icyflame/gyft/commit/de41c402fa54831e8cc473a68097f1ffa2034ce2

It's un-tested code, I wrote it in a hurry. I will polish this up and send a better PR soon, if this problem is something that everyone on the KGP network is having.
