### ISSUE TITLE
User preference file

### ISSUE THREAD

**Issue by athityakumar** [metakgp/gyft#30]
Add a user preference file which contains the semantics of the message to be added onto the Google Calendar. This will preferably be a `yaml` / `json` / `md` file - which will be `gitignore`-d.

```
class: "Class of "
lab: "Lab of "
```

On the web portal of `gyft`, this can be taken as input (rather than a file) from the user before syncing.

**Comment by thealphadollar** [comment]
I don't think this is required. Adds a level of information on top of already enough information. We have found a better way of deleting events added by GYFT.
