### ISSUE TITLE
Enable gyft to create the recurrence schedule from given set of date and times

### ISSUE THREAD

**Issue by icyflame** [metakgp/gyft#33]
The script will begin with the following list of lists:

```[ [ BEGIN_1, END_1 ], [ BEGIN_2, END_2 ], [ BEGIN_3, END_3 ], ...]```

The events that are created will be created only in between these dates. i.e. timetable events won't be created for the time between `END_1` and `BEGIN_2` etc.

Once implemented, this can be easily improved to include both vacations (Durga Puja), mid-term, end-term, holidays (from the holiday list).

Do this in both the available flows:

- [x] ICS generation
- [ ] Google Calendar Sync

**Comment by icyflame** [comment]
Patch for first part of this issue: #35

**Comment by icyflame** [comment]
First part of this issue solved in #35

**Comment by proffapt** [comment]
What does `Google Calendar Sync` mean here? Couldn't understand it.

**Comment by proffapt** [comment]
Syncing of google calendar already existed (don't know it was before or after this issue but it exists).
Creating a new issue for including institute holidays from the academic calendar and institute's website.

Hence, closing this one.
