### ISSUE TITLE
Unable to access timetable

### ISSUE THREAD

**Issue by harishnandan** [metakgp/gyft#37]
In the 1st format of timetable I am able to store the timetable to data.txt
![24172300_767665296757199_811219488_n](https://user-images.githubusercontent.com/24224542/33482497-540b6836-d6bf-11e7-9ec6-bd70e90876ee.jpg)

While in the 2nd format it generates an error
![24172705_767665293423866_2133369572_n](https://user-images.githubusercontent.com/24224542/33482532-8240caca-d6bf-11e7-9e20-a6d5e03ed97a.jpg)

The error is following:
![24273086_767665473423848_1914279008_n](https://user-images.githubusercontent.com/24224542/33482719-6b0e7586-d6c0-11e7-9664-5e648aace418.jpg)

**Comment by icyflame** [comment]
What are the first and second formats?

**Comment by harishnandan** [comment]
I don't know. I was unable to run gyft.py with my roll no so I tried my friend's and it ran nicely. On checking ERP I found that we both had different timetable format.I am not sure why they are different.

**Comment by icyflame** [comment]
This is related to #18, we would love if you could figure out the reason and solve this. 

I am closing this now, thanks for the feedback! :smile:
