### ISSUE TITLE
Make it image compatible

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/gyft#40]
Currently we ask the user to input password and, for obvious reasons, it's a bad practice.

A better way to do this would be using OCR and identifying elements by reading the image of time table taken using any device,  or in the very least, just the actual timetable.

@ghostwriternr Any other spec you'd like to see? Assign to me :)

**Comment by ghostwriternr** [comment]
Asking the user to input password isn't the bad practice. But when converting this to a web app, we're making them send naked passwords over the network, which is bad. OCR should be a great way to do it, but I'd like to see it as a separate repo (since it would be different from the ground up). The input would simply be a screenshot to this.

No other specs that I can think of right now.

**Comment by ghostwriternr** [comment]
I started work on this a while ago, but couldn't get back to it. If you're interested in building this, you can contribute to the repo here: https://github.com/ghostwriternr/gyft-ss

**Comment by thealphadollar** [comment]
@ghostwriternr C? Seriously? :/

**Comment by thealphadollar** [comment]
Who uses it when we have python?

Anyways I will continue this since I want to program something in cpp also.

Shivam Kumar Jha
First Year Undergraduate
Coordinator [Computer Science And Engineering Department Society]
IIT Kharagpur

**Comment by icyflame** [comment]
I am closing this issue now.

Personally, I think that the project [gyft2](https://github.com/xypnox/gyft2) that asks the users to save a HTML file and then builds the timetable from that is deterministic and an easy method of avoiding asking the user for a password. (In fact, I think I will be bringing @xypnox into the loop, and migrating that functionality to this repository for users who don't want to share passwords with us.

**Comment by icyflame** [comment]
@ghostwriternr can you please detail your concerns here?

We will be accepting the HTML file as a text file upload, and we will _not_ be executing or serving it anywhere. Simply reading and parsing it. So, any script included in the file will never be executed. I would love to know what you guys' concerns were in more detail.
