### ISSUE TITLE
Make webapp 

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/gyft#41]
Current web app is based on the password model which will be replaced with the OCR model and hence we require a new web app. 

Under this web app, the user will be able to submit an image and download the ICS file after all the backend work is done.

@ghostwriternr assign me please.

**Comment by ghostwriternr** [comment]
Can we keep this as a part of the dashboard? I'd much prefer to see this there. The more separate frontends we build, the harder we make it for people to find them.

We _can_ have 3 ways to get their timetables there:
1. ERP credentials way
2. HTML file (although I'm very sceptical about this. Security issues?)
3. Screenshot

**Comment by ghostwriternr** [comment]
Closing this issue here. Redirect to: https://github.com/metakgp/dashboard-beta
