### ISSUE TITLE
Implement REGEX Check With RollNo

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/gyft#53]
Currently, we do not check for the validation of roll numbers entered.

In practicality it is not feasible to verify if the roll number is correct but
we can surely filter wrong formatted rolls numbers using REGEX check.

https://regexone.com/

**Comment by icyflame** [comment]
@thealphadollar we discussed this earlier as well. Invalid roll numbers will be rejected by ERP. There is no value addition if we do the check before sending it to the ERP. I don't see the point of having that logic here.

When the regex changes in the future, it will lead to more work for anyone trying to figure out why Gyft isn't working.

**Comment by icyflame** [comment]
> but then asking a user to enter his or her roll number itself is pointless thing

I don't understand why not having a regex check makes the user entering their roll number pointless. :)

**Comment by venkateshthondamallu** [comment]
> > but then asking a user to enter his or her roll number itself is pointless thing
> 
> I don't understand why not having a regex check makes the user entering their roll number pointless. :)

I think it's better to have an extension for that criteria inorder to avoid the user to input a random thing..btw it's not at all a big task. With your permission if i want to move further please let me know..

**Comment by thealphadollar** [comment]
@venkateshthondamallu It's obviously not a big task but it is an unnecessary one and something which might increase our workload if the method of roll numbers is changed in the future.

**Comment by venkateshthondamallu** [comment]
@thealphadollar yeah thats fine. Then i would work on other issue.
 Thanks
