### ISSUE TITLE
Not repeating weekly 

### ISSUE THREAD

**Issue by ACakshay** [metakgp/gyft#62]
after adding to Google calendar, its default setting it to repeat till 2018
can be repeated till the week end

**Comment by thealphadollar** [comment]
Hey @ACakshay can you please elaborate on the issue you are facing? I'm unable to get the problem being faced.

**Comment by ACakshay** [comment]
@thealphadollar when the timetable is added to calendar it should repeat weekly till the end of semester except for mid-sem and end-sem but when I added it to calendar it is not working like that
