### ISSUE TITLE
Import Error in Google Calendar

### ISSUE THREAD

**Issue by grapheo12** [metakgp/gyft#65]
ICS file generated from Gyft cannot be imported to Google Calendar.

Steps to reproduce:
===============

1. Generate .ics file from gyft.
2. Go to google calendar on desktop. Click Settings icon on the top right. 
3. Go to Import and Export tab.
4. Upload the downloaded file.
5. Click import.

Screenshot:
=========

![2020-01-03_23-59](https://user-images.githubusercontent.com/16435932/71741540-2dac0e00-2e85-11ea-8bad-ba96b296434d.png)

**Comment by grapheo12** [comment]
On a sidenote, Evolution calendar can read the file but it does not add it to the calendar even after a successful import

**Comment by themousepotato** [comment]
@grapheo12 i think `dates.py` needs update.

**Comment by thealphadollar** [comment]
This should be create in gyft-serve and not here. @grapheo12
