### ISSUE TITLE
Migrating from the concept of subject.json

### ISSUE THREAD

**Issue by proffapt** [metakgp/gyft#88]
The idea is pretty simple, we don't have to maintain a `subjects.json` for fetching the name of the course. We can directly fetch it from erp itslef.

Possible solutions:
- Using department timetable, with some trickery to get it
- Using the concept from [gyfe](https://github.com/ashwinpra/gyfe)

**Comment by chirag-ghosh** [comment]
@ashwinpra

**Comment by ashwinpra** [comment]
On it.
