### ISSUE TITLE
Ask the user about generating ics file

### ISSUE THREAD

**Issue by proffapt** [metakgp/gyft#91]
Instead of just printing to use `generate_ics.py` in the end of `gyft.py`, prompt the user for confirmation whether they want ics file or not and if yes we can just directly execute the `generate_ics.py` script.

Same goes for `add_events.py`

And integrate `del_events.py` via a cli argument what they want to do. Basically one should only use `gyft.py` for whatever their need be

> **Note** I am not clear about the role of `del_events.py` so let's first of al complete the first two tasks and if you know what the other file does please tell me.

**Comment by chirag-ghosh** [comment]
One issue needs to be taken care of. Suppose there occurs some error in finding the course name. The `data.txt` wont have it and the user needs to enter it manually. In such a senario, we should warn the user about running `generate_ics.py`

**Comment by proffapt** [comment]
> One issue needs to be taken care of. Suppose there occurs some error in finding the course name. The `data.txt` wont have it and the user needs to enter it manually. In such a senario, we should warn the user about running `generate_ics.py`

These are edge cases, obviously needed to be handled.

**Comment by proffapt** [comment]
@ashwinpra reply here if you will do it, so that it will be assigned to you

**Comment by ashwinpra** [comment]
> @ashwinpra reply here if you will do it, so that it will be assigned to you

Sure, I can work on it.

**Comment by ashwinpra** [comment]
I can think of two options: 
- Based on user input, run `generate_ics.py` as a subprocess within `gyft.py`
- Remove the `main` function from `generate_ics.py`, and all the functions can be imported into `gyft.py`, and again based on user input, the functions are executed as required to generate ICS within `gyft.py` itself

Second option would be better I suppose

**Comment by proffapt** [comment]
The second method is preferable.

**Comment by proffapt** [comment]
Being worked on #96
