### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by ashwinpra** [metakgp/gyft#93]
- [x] Changes made in #96  - solved in #98
- [x] Make instructions more organised and concise - using better format, preferably [this](https://github.com/proffapt/myREADME) - solved in #110 
- [ ] A logo?

**Comment by proffapt** [comment]
2 - @ashwinpra 
3 - @harshkhandeparkar

**Comment by shikharsoni07** [comment]
@proffapt 
> Make instructions more organised and concise - using better format, preferably [this](https://github.com/proffapt/README)

that link does not work.

**Comment by proffapt** [comment]
> that link does not work.

fixed 👌🏻

**Comment by proffapt** [comment]
@harshkhandeparkar need your generous support, please reply here so that I can assign you this issue.

**Comment by shikharsoni07** [comment]
@proffapt 
i would like to work on this.

**Comment by harshkhandeparkar** [comment]
> @harshkhandeparkar need your generous support, please reply here so that I can assign you this issue.

.

**Comment by jainsujan11** [comment]
I would like to work on making better readme.
Could you guys give me some direction

**Comment by proffapt** [comment]
> I would like to work on making better readme. Could you guys give me some direction

Replied on slack. We will carry the future conversation  there only.

**Comment by shikharsoni07** [comment]
@proffapt 
Could make a demo video. Any specifics?

**Comment by proffapt** [comment]
> @proffapt Could make a demo video. Any specifics?

Such demo videos should be:
- short
- To the point (like don't show them what command you typed, just how it works)
   - what you can do is, combine a few short clips + screenshots of result like that in calendar
etc etc..

But do it after #111 this is merged.

**Comment by proffapt** [comment]
Video peace maarte, too much hastel for every release/change we do here...
A logo is a good to have..
