### ISSUE TITLE
Remove `data.txt` as a middleware

### ISSUE THREAD

**Issue by proffapt** [metakgp/gyft#99]
It might be useful back then but not now.
If required to create something  other than just `timetable.ics` (Like - time table pdf or timetable CLI representation) we can directly use `timetable_dict`.

This is just an overhead at this point

**Comment by shikharsoni07** [comment]
Hello, can I work on this? Looks easy enough for a newbie.

**Comment by proffapt** [comment]
Interesting, go ahead!

**Comment by ashwinpra** [comment]
Closed with #107
